services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ~/volumes/codecake/postgresql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=m0h@mm3d
      - POSTGRES_USER=falih
    ports:
      - 127.0.0.1:5434:5432